trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformCLI@1
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
      allowTelemetryCollection: true    

  - task: TerraformDrift@1
    inputs:
      workingDirectory: 'terraform'